name: terraform-plan workflow

on:
  push:
    branches:
      - main

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform format checking
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Run TFLint
        run: tflint

  plans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Initialize terraform
        run: terraform init

      - name: Terraform plan
        id: tf-plan
        run: terraform plan -out=tfplan

      - name: Save plan output
        if: ${{ steps.tf-plan.outcome == 'failure' || steps.tf-plan.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan